import { Providers } from "@/provider/provider";

export const metadata = {
  title: 'Linkeep',
  description: 'Generated by Linkeep',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
